### ISSUE TITLE
Option to allow html for attributes like confirm, titletxt, canceltxt and confirmtxt

### ISSUE THREAD

**Issue by AgentSmith0** [dealfonso/power-buttons#1]
What about adding an option to accept html values for attributes like confirm, titletxt, canceltxt and confirmtxt. This would allow more customization, e.g. by adding icons tags, etc.

**Comment by dealfonso** [comment]
hi, nice point. I will change the use of "textContent" to "innerHTML" in the next version

**Comment by AgentSmith0** [comment]
Thank you very much!

**Comment by AgentSmith0** [comment]
Hi, do you have an ETA for the next update?

**Comment by dealfonso** [comment]
I hope to have a new major version by the end of the week (I need to write the README ;) ):
- it has some major changes like changes of the name of the attributes
- it has more actions (e.g. button that simply shows a message, button that sets the values of a form, etc.)
- a new name for the library

**Comment by AgentSmith0** [comment]
Very nice, thank you for your work!

**Comment by AgentSmith0** [comment]
Is it ok for you to publish the changes you made so far in a seperate branch, maybe I can help testing the new features and writing docs for it. Thanks!

**Comment by dealfonso** [comment]
Sorry but while writing docs I realized of some problems and I am rewriting parts of the code. I'll have a new branch soon

**Comment by AgentSmith0** [comment]
Is there anything I can help, so that we get the new version out?

**Comment by AgentSmith0** [comment]
@dealfonso Any updates on this?

**Comment by dealfonso** [comment]
hi, I was on holidays... I'll be back on this soon

**Comment by dealfonso** [comment]
Hi,

I have uploaded a new branch, with a whole new version for the library (with even a new name), that adds new types of buttons... and also enables adding even more buttons.

In the new version, now I have:
- confirmbutton (which shows a confirmation dialog, prior to executing the action)
- verify, (which executes a javascript code and continues or not, depending on the result)
- showmessage, (which simply shows a modal)
- formset, (which sets the values of a form)

I have the plan of adding (at least) two new buttons:
- formbutton, which replaces the current button with a form that is to be submitted (along with payload fields)
- workbutton, which shows a dialog, executes a long-running task and hides when it has ended.

I'd like to have your feedback, if possible.

The new branch is https://github.com/dealfonso/jsconfirm-buttons/tree/power-buttons, and there is a "devel.html" example that includes the working buttons.

I'll close this comment, and let's start a new comment if needed.

**Comment by AgentSmith0** [comment]
Thank you very much for your work! The declarative way works fine, but I haven't found out how to show a confirm modal or alert message programmatically...

**Comment by dealfonso** [comment]
the functions are not yet exported in the current version.

Please address new questions to issue #3
