### ISSUE TITLE
not dependent on buttons

### ISSUE THREAD

**Issue by novalhabibi** [dealfonso/power-buttons#15]
hey bro
how do I avoid being dependent on buttons, I want to implement it with  https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.js
like this

<script type="text/javascript">
		$.validator.setDefaults( {
			submitHandler: function () {
           //show  the modal
           			}
		} );
		</script>
		
		thks

**Comment by dealfonso** [comment]
sorry, but I did not understand the question... what do you want to do?
