### ISSUE TITLE
new version: power-buttons

### ISSUE THREAD

**Issue by dealfonso** [dealfonso/power-buttons#3]
In the new version:

- _confirmbutton_: shows a confirmation dialog before executing the action
- _verify_: executes a javascript code and continues or not, depending on the result
- _showmessage_: simply shows a modal
- _formset_: sets the values of a form

The idea is to add (at least) two new buttons:
- _formbutton_: replaces the current button with a form that is to be submitted (along with payload fields)
- _taskbutton_: shows a modal dialog, executes a long-running task, and hides when it has ended.

The new branch is https://github.com/dealfonso/jsconfirm-buttons/tree/power-buttons, and there is a "devel.html" example that includes the working buttons.

**Comment by AgentSmith0** [comment]
Initializing powerButtons programmatically works fine. The utilities functions are very useful too. Thanks!

**Comment by dealfonso** [comment]
Thank you for reviewing this version... I uploaded the new plugins: _asynctask_ and _formbutton_. Could you please test them and give some feedback?

**Comment by AgentSmith0** [comment]
Both new plugins work fine here, great work! Maybe an optional cancel button for the asynctask plugin would be nice to have...

**Comment by dealfonso** [comment]
Hi, the button is there... it appears in case you provide a cancel callback.

**Comment by AgentSmith0** [comment]
@dealfonso What about disabling the debug messages like "Registering action ..." by default. Currently they always appear, so an option would be nice to have.

**Comment by AgentSmith0** [comment]
@dealfonso What do you think of adding an option to disable the debug messages?

**Comment by dealfonso** [comment]
Sorry... They should be completely removed.

**Comment by dealfonso** [comment]
The new release [2.0.1](https://github.com/dealfonso/power-buttons/releases/tag/2.0.1) removes the comments (among other things)
